#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flrig
Version  : 1.3.54
Release  : 10
URL      : https://sourceforge.net/projects/fldigi/files/flrig/flrig-1.3.54.tar.gz
Source0  : https://sourceforge.net/projects/fldigi/files/flrig/flrig-1.3.54.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: flrig-bin = %{version}-%{release}
Requires: flrig-data = %{version}-%{release}
Requires: flrig-license = %{version}-%{release}
BuildRequires : fltk-dev
BuildRequires : fontconfig-dev
BuildRequires : libXcursor-dev
BuildRequires : libXft-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(x11)

%description
Flrig is a transceiver control program for Amateur Radio use.  It does
not use any 3rd party transceiver control libraries.  It is a c++ pro-
gram that encapsulates each transceiver in it's own class.  Where ever
possible the transceiver class(s) use polymorphism to reuse code that
is portable across a series of transceivers.

%package bin
Summary: bin components for the flrig package.
Group: Binaries
Requires: flrig-data = %{version}-%{release}
Requires: flrig-license = %{version}-%{release}

%description bin
bin components for the flrig package.


%package data
Summary: data components for the flrig package.
Group: Data

%description data
data components for the flrig package.


%package license
Summary: license components for the flrig package.
Group: Default

%description license
license components for the flrig package.


%prep
%setup -q -n flrig-1.3.54
cd %{_builddir}/flrig-1.3.54

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612367580
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1612367580
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flrig
cp %{_builddir}/flrig-1.3.54/COPYING %{buildroot}/usr/share/package-licenses/flrig/b47456e2c1f38c40346ff00db976a2badf36b5e3
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flrig

%files data
%defattr(-,root,root,-)
/usr/share/applications/flrig.desktop
/usr/share/pixmaps/flrig.xpm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flrig/b47456e2c1f38c40346ff00db976a2badf36b5e3
