#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : flrig
Version  : 2.0.03
Release  : 26
URL      : https://sourceforge.net/projects/fldigi/files/flrig/flrig-2.0.03.tar.gz
Source0  : https://sourceforge.net/projects/fldigi/files/flrig/flrig-2.0.03.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: flrig-bin = %{version}-%{release}
Requires: flrig-data = %{version}-%{release}
Requires: flrig-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : fltk-dev
BuildRequires : fontconfig-dev
BuildRequires : libXcursor-dev
BuildRequires : libXft-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(x11)
BuildRequires : systemd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Flrig is a transceiver control program for Amateur Radio use.  It does
not use any 3rd party transceiver control libraries.  It is a c++ pro-
gram that encapsulates each transceiver in it's own class.  Where ever
possible the transceiver class(s) use polymorphism to reuse code that
is portable across a series of transceivers.

%package bin
Summary: bin components for the flrig package.
Group: Binaries
Requires: flrig-data = %{version}-%{release}
Requires: flrig-license = %{version}-%{release}

%description bin
bin components for the flrig package.


%package data
Summary: data components for the flrig package.
Group: Data

%description data
data components for the flrig package.


%package license
Summary: license components for the flrig package.
Group: Default

%description license
license components for the flrig package.


%prep
%setup -q -n flrig-2.0.03
cd %{_builddir}/flrig-2.0.03
pushd ..
cp -a flrig-2.0.03 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693006820
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1693006820
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flrig
cp %{_builddir}/flrig-%{version}/COPYING %{buildroot}/usr/share/package-licenses/flrig/b47456e2c1f38c40346ff00db976a2badf36b5e3 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/flrig
/usr/bin/flrig

%files data
%defattr(-,root,root,-)
/usr/share/applications/flrig.desktop
/usr/share/pixmaps/flrig.xpm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flrig/b47456e2c1f38c40346ff00db976a2badf36b5e3
